name: Coding Standard & Static Analysis

on:
  workflow_call:
    inputs:
      check_tests:
        description: 'Whether to run static analysis for tests'
        required: false
        type: boolean

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  cs-stan:
    name: Coding Standard & Static Analysis
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, intl
        coverage: none
        tools: cs2pr, vimeo/psalm:5.4, phpstan:1.9
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Composer install
      uses: ramsey/composer-install@v2

    - name: Run phpcs
      run: vendor/bin/phpcs --report=checkstyle src/ tests/ | cs2pr

    - name: Run psalm
      if: always()
      run: psalm --output-format=github

    - name: Run phpstan
      if: always()
      run: phpstan analyse --error-format=github

    - name: Run phpstan for tests
      if: ${{ inputs.check_tests }}
      run: phpstan analyse -c tests/phpstan.neon --error-format=github
