name: Coding Standard & Static Analysis

on:
  workflow_call:

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  cs-stan:
    name: Coding Standard & Static Analysis
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, intl
        coverage: none
        tools: cs2pr, vimeo/psalm:5.0.0-beta1, phpstan:1.9

    - name: Composer install
      uses: ramsey/composer-install@v2

    - name: Run phpcs
      run: vendor/bin/phpcs --report=checkstyle src/ tests/ | cs2pr

    - name: Run psalm
      if: always()
      run: psalm --output-format=github

    - name: Run phpstan
      if: always()
      run: phpstan analyse --error-format=github
