name: Coding Standard & Static Analysis

on:
  workflow_call:
    inputs:
      check_tests:
        description: 'Whether to run static analysis for tests'
        required: false
        type: boolean
      phive_keys:
        description: 'GPG key signatures for phive packages. Should be comma separated string "800d,d44d"'
        required: false
        default: 'CF1A108D0E7AE720,51C67305FFC2E5C0,12CE0F1D262429A5'
        type: string

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  cs-stan:
    name: Coding Standard & Static Analysis
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, intl
        coverage: none
        tools: phive, cs2pr
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Composer install
      uses: ramsey/composer-install@v2

    - name: Install PHP tools with phive.
      run: "phive install --trust-gpg-keys '${{ inputs.phive_keys }}'"

    - name: Run phpcs
      if: always()
      run: vendor/bin/phpcs --report=checkstyle src/ tests/ | cs2pr

    - name: Run psalm
      if: always()
      run: tools/psalm --output-format=github

    - name: Run phpstan
      if: always()
      run: tools/phpstan analyse --error-format=github

    - name: Run phpstan for tests
      if: ${{ inputs.check_tests }}
      run: tools/phpstan analyse -c tests/phpstan.neon --error-format=github
