name: Testsuite without DB

on:
  workflow_call:

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  testsuite-linux:
    runs-on: ubuntu-22.04
    continue-on-error: ${{ matrix.unstable }}
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.1']
        dependencies: [highest]
        unstable: [false]
        include:
          - php-version: '8.1'
            dependencies: lowest
            unstable: false
          - php-version: '8.2'
            dependencies: highest
            unstable: false
          - php-version: '8.3'
            dependencies: highest
            unstable: false

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, intl
        ini-values: zend.assertions=1
        coverage: pcov

    - name: Composer install
      uses: ramsey/composer-install@v2
      with:
        dependency-versions: ${{ matrix.dependencies }}
        composer-options: ${{ matrix.composer-options }}

    - name: Run PHPUnit
      run: |
        if [[ ${{ matrix.php-version }} == '8.1' && ${{ matrix.dependencies }} == 'highest' ]]; then
          export CODECOVERAGE=1 && vendor/bin/phpunit --display-deprecations --display-incomplete --display-skipped --coverage-clover=coverage.xml
        else
          vendor/bin/phpunit --display-deprecations
        fi

    - name: Code Coverage Report
      if: success() && matrix.php-version == '8.1' && matrix.dependencies == 'highest'
      uses: codecov/codecov-action@v3
