name: Testsuite with DB

on:
  workflow_call:

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  testsuite-linux:
    runs-on: ubuntu-22.04
    continue-on-error: ${{ matrix.unstable }}
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.1']
        db-type: [mysql, pgsql]
        dependencies: ['highest']
        unstable: [false]
        include:
          - php-version: '8.1'
            db-type: 'sqlite'
            dependencies: 'lowest'
          - php-version: '8.2'
            db-type: 'mysql'
          - php-ersion: '8.3'
            composer-options: "--ignore-platform-reqs"
            unstable: true

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres

    steps:
    - uses: actions/checkout@v4

    - name: Setup Service
      if: matrix.db-type == 'mysql'
      run: |
        sudo service mysql start
        mysql -h 127.0.0.1 -u root -proot -e 'CREATE DATABASE cakephp;'

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, intl, pdo_${{ matrix.db-type }}
        ini-values: zend.assertions=1
        coverage: pcov

    - name: Composer install
      uses: ramsey/composer-install@v2
      with:
        dependency-versions: ${{ matrix.dependencies }}
        composer-options: ${{ matrix.composer-options }}

    - name: Run PHPUnit
      run: |
        if [[ ${{ matrix.db-type }} == 'sqlite' ]]; then
          export DB_URL='sqlite:///:memory:'
        fi
        if [[ ${{ matrix.db-type }} == 'mysql' ]]; then
          export DB_URL='mysql://root:root@127.0.0.1/cakephp'
        fi
        if [[ ${{ matrix.db-type }} == 'pgsql' ]]; then
          export DB_URL='postgres://postgres:postgres@127.0.0.1/postgres'
        fi
        if [[ ${{ matrix.php-version }} == '8.1' && ${{ matrix.db-type }} == 'mysql' ]]; then
          vendor/bin/phpunit --display-deprecations --display-incomplete --display-skipped  --coverage-clover=coverage.xml
        else
          vendor/bin/phpunit --display-deprecations
        fi

    - name: Code Coverage Report
      if: success() && matrix.php-version == '8.1' && matrix.db-type == 'mysql'
      uses: codecov/codecov-action@v3
